### ISSUE TITLE
OpenTTD opt-in Survey - is a DPIA needed?

### ISSUE THREAD

**Issue by andythenorth** [OpenTTD/survey-web#3]
OpenTTD opt-in Survey - is a DPIA needed?
=========================================

Background
----------

OpenTTD proposes to use an opt-in survey to collect anomymised data about player's use of the OpenTTD game ("the game") and the game client software ("the game client").

This data will be analysed to better inform decisions about the design and operation of the game.

The collection and analysis together constitute a data processing activity.

This activity has been designed using privacy-by-design principles, and to comply with regulatory regimes including the European Union General Data Protection Regulation (GDPR).

A more in-depth rationale and technical details about the implementation of this activity are found at https://github.com/OpenTTD/OpenTTD/pull/10719

Purpose of the data processing activity
---------------------------------------

The purpose of the data processing activity is to inform decisions about the design and operation of the game.

No personal identifying information of any kind is required to perform this activity.

Scope of processing
-------------------

For this activity data is processed in **2** independent scopes.

**1. The survey collection activity**

Data will be collected via the game client.
This will be on an opt-in basis, with clear consent from the user.
The data will record information about user choices and the environment in which the game is being used, including

* game settings
* metadata such as how long a specific savegame has been played
* information about the host environment such as operating system and CPU

The data will be transmitted by the game client to an online collection tool ("the survey collector").

The data is guaranteed anonynmous before transmission to the survey collector.

Data will be analysed by the developers / operators of OpenTTD, manually or using automated means.

Results of analysis may be published by the developers / operators of OpenTTD, for example to a "survey results" website.  This publishing may use manual or automated means.

**2. Network and information security**

Per Recital 49 of the GDPR, personal information may be processed to the extent strictly necessary and proportionate for the purposes of ensuring network and information security.

For this activity, personal information will be processed to detect, prevent, mitigate or remedy network and information security risks.

For example, the IP address of the client where a transmission originated may be processed.

The dataset collected under this network and information security scope is processed entirely independently from the survey collection dataset.  The datasets cannot be rejoined by technical means.

Data subjects
-------------

**For the survey collection activity**

_Potential data subjects_ are:
* users of the game client who **choose** to opt-in and send survey data
* however as **no personal information is collected**, there are **no** data subjects for this collection activity

**For the network and information security activity**

Data subjects are
* users of the game client who **choose** to opt-in and send survey data
* this processing is only to the extent strictly necessary and proportionate, as permitted and governed by Recital 49 of the GDPR

Is a DPIA needed? - evaluation
------------------------------

The European Commission provides guidance for assessing whether a Data Protection Impact Assessment (DPIA) is required for a processing activity.

This guidance can be found at https://ec.europa.eu/newsroom/just/document.cfm?doc_id=47711

**The following criteria have been applied to the data processing activity:**

1. . Evaluation or scoring, including profiling and predicting, especially from “aspects concerning the data subject's performance at work, economic situation, health, personal preferences or interests, reliability or behavior, location or movements”

None.

2. Automated-decision making with legal or similar significant effect: processing that aims at taking decisions on data subjects producing “legal effects concerning the natural person” or which “similarly significantly affects the natural person”

None.

3. Systematic monitoring: processing used to observe, monitor or control data subjects, including data collected through networks or “a systematic monitoring of a publicly accessible area”

None.

The network and information security activity does not entail a high risk under this criteria as that processing is not systematic: the data subject opts-in to that processing, is aware that they are doing so, and can avoid being subject to such processing.

4.  Sensitive data or data of a highly personal nature: this includes special categories of personal data as defined in Article 9 (for example information about individuals’ political opinions), as well as personal data relating to criminal convictions or offences as defined in Article 10.

None

5. Data processed on a large scale: the GDPR does not define what constitutes large-scale, though recital 91 provides some guidance.

None.  Recital 91 was used to determine that the processing activity does not entail a high risk under this criteria.

6. Matching or combining datasets, for example originating from two or more data processing operations performed for different purposes and/or by different data controllers in a way that would exceed the reasonable expectations of the data subject.

None.

7. Data concerning vulnerable data subjects (recital 75): the processing of this type of data is a criterion because of the increased power imbalance between the data subjects and the data controller, meaning the individuals may be unable to easily consent to, or oppose, the processing of their data, or exercise their rights.  Vulnerable data subjects may include children (they can be considered as not able to knowingly and thoughtfully oppose or consent to the processing of their data), employees , more vulnerable segments of the population requiring special protection (mentally ill persons, asylum seekers, or the elderly, patients, etc.), and in any case where an imbalance in the relationship between the position of the data subject and the controller can be identified.

None.

For this criteria, the risk of collecting data from children (or other vulnerable data subjects) was considered, as OpenTTD is a game and children (or other vulnerable data subjects) may play it.
The survey collection activity is anonymised and therefore does not entail a high risk to data subjects under this criteria.
The network and information security activity uses only widely-used industry-standard techniques, and does not represent a high risk to data subjects under this criteria.

8. Innovative use or applying new technological or organisational solutions, like combining use of finger print and face recognition for improved physical access control, etc.

None.

9. When the processing in itself “prevents data subjects from exercising a right or using a service or a contract” (Article 22 and recital 91).

None.

10. Other criteria that should be considered due to the unique or innovative nature of the processing.

None.

Is a DPIA needed? - conclusion
------------------------------

No criteria are met which would require a DPIA to be carried out.

**Therefore no DPIA is required for this processing activity**.

**Comment by TrueBrain** [comment]
Thank you for this @andythenorth . I am going to close this issue, not because I disagree, but because there is no more work to be done here. Anyone curious can always refer to this issue for further detail.

Again, tnx for doing this :)
